# fly.toml app configuration file generated for sinuelo-finance-api on 2025-08-19T14:53:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sinuelo-finance-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"
  
[env]
  PORT = "8080"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true   # liga/desliga automático p/ economizar
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/"
	
[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1