# fly.toml app configuration file generated for sinuelo-finance-api on 2025-08-19T14:53:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sinuelo-finance-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"
  
[env]
  PORT = "8080"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true   # liga/desliga automático p/ economizar
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"