"""add ativo to conta and categoria

Revision ID: 8634ce8fd1fc
Revises: 58860d3399ca
Create Date: 2025-08-31 18:29:20.670117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8634ce8fd1fc'
down_revision: Union[str, Sequence[str], None] = '58860d3399ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('ativo', sa.Boolean(), nullable=True, server_default=sa.true()))
    op.add_column('conta', sa.Column('ativo', sa.Boolean(), nullable=True, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta', 'ativo')
    op.drop_column('categoria', 'ativo')
    # ### end Alembic commands ###
